using System.Text;
using YakuzaDeadSouls.Ps3;

namespace YakuzaDeadSouls.ApClient;

// Writes world/yakuza_dead_souls/Data.py from ApIds. Everything is emitted
// fully expanded so the apworld does no computation - it just reads tables.
public static class WorldEmitter
{
    private static string Py(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    public static string Render()
    {
        var b = new StringBuilder();
        b.AppendLine("# GENERATED by `ydsclient --emit-world`. Do not edit.");
        b.AppendLine("# The source of truth is client/ApClient/ApIds.cs.");
        b.AppendLine();
        b.AppendLine($"GAME_NAME = {Py(ApIds.GameName)}");
        b.AppendLine($"BASE_ID = {ApIds.BaseId}");
        b.AppendLine();

        // --- items: name -> (id, classification) ---
        b.AppendLine("# item name -> (id, classification)");
        b.AppendLine("ITEM_TABLE = {");
        b.AppendLine($"    {Py("Erika's Business Card")}: ({ApIds.ErikaCard}, \"progression\"),");
        b.AppendLine($"    {Py("Yuna's Business Card")}: ({ApIds.YunaCard}, \"progression\"),");
        // Abilities are items only - nothing gates on them, so nothing needs to
        // be `progression`.
        for (var i = 0; i < Abilities.Count; i++)
            b.AppendLine($"    {Py(Abilities.All[i].Name)}: ({ApIds.AbilityItemId(i)}, \"useful\"),");
        for (var t = 0; t < ApIds.AmmoTypes.Length; t++)
            for (var r = ApIds.AmmoMin; r <= ApIds.AmmoMax; r++)
                b.AppendLine($"    {Py(ApIds.AmmoItemName(t, r))}: " +
                             $"({ApIds.AmmoItemId(t, r)}, \"filler\"),");
        foreach (var id in ApIds.VanillaShopItems)
        {
            var nm = Inventory.KnownItems.TryGetValue(id, out var known) ? known : null;
            if (nm is null || Inventory.IsPlaceholder(nm)) continue;
            b.AppendLine($"    {Py(nm)}: ({ApIds.GameItemId(id)}, \"filler\"),");
        }
        foreach (var (id, name) in ApIds.Guns)
            b.AppendLine($"    {Py(name)}: ({ApIds.GameItemId(id)}, \"useful\"),");
        for (var i = 0; i < ApIds.MoneyAmounts.Length; i++)
            b.AppendLine($"    {Py(ApIds.MoneyItemName(ApIds.MoneyAmounts[i]))}: " +
                         $"({ApIds.MoneyBase + i}, \"filler\"),");
        b.AppendLine("}");
        b.AppendLine();

        // --- locations ---
        b.AppendLine("# location name -> id");
        b.AppendLine("LOCATION_TABLE = {");
        for (var song = 0; song < ApIds.SongNames.Length; song++)
        {
            if (!ApIds.Reachable(ApIds.SongCharacters[song])) continue;
            for (var tier = 0; tier < ApIds.ScoreTiers.Length; tier++)
                b.AppendLine($"    {Py(ApIds.KaraokeLocationName(song, ApIds.ScoreTiers[tier]))}: " +
                             $"{ApIds.KaraokeLocationId(song, tier)},");
        }
        for (var level = 2; level <= ApIds.MaxLevel; level++)
            b.AppendLine($"    {Py(ApIds.LevelLocationName(level))}: " +
                         $"{ApIds.LevelLocationId(level)},");
        for (var sh = 0; sh < ApIds.ShopDefs.Length; sh++)
        {
            var def = ApIds.ShopDefs[sh];
            if (!ApIds.Reachable(def.Who)) continue;
            for (var slot = 0; slot < def.Slots; slot++)
                b.AppendLine($"    {Py(ApIds.ShopLocationName(def, slot))}: " +
                             $"{ApIds.ShopLocationId(sh, slot)},");
        }
        b.AppendLine("}");
        b.AppendLine();

        // --- character scoping ---
        b.AppendLine("# Bit per character. An item may sit at a location only when every");
        b.AppendLine("# character who needs it can reach that location - see MayPlace in ApIds.cs.");
        b.AppendLine($"CHAR_NONE = {(int)ApIds.Characters.None}");
        b.AppendLine($"CHAR_AKIYAMA = {(int)ApIds.Characters.Akiyama}");
        b.AppendLine($"CHAR_MAJIMA = {(int)ApIds.Characters.Majima}");
        b.AppendLine($"CHAR_GODA = {(int)ApIds.Characters.Goda}");
        b.AppendLine($"CHAR_KIRYU = {(int)ApIds.Characters.Kiryu}");
        b.AppendLine($"CHAR_FINALE = {(int)ApIds.Characters.Finale}");
        b.AppendLine();

        b.AppendLine("# location name -> characters who can reach it");
        b.AppendLine("LOCATION_CHARACTERS = {");
        for (var song = 0; song < ApIds.SongNames.Length; song++)
        {
            if (!ApIds.Reachable(ApIds.SongCharacters[song])) continue;
            foreach (var tier in ApIds.ScoreTiers)
                b.AppendLine($"    {Py(ApIds.KaraokeLocationName(song, tier))}: " +
                             $"{(int)ApIds.SongCharacters[song]},");
        }
        for (var level = 2; level <= ApIds.MaxLevel; level++)
            b.AppendLine($"    {Py(ApIds.LevelLocationName(level))}: " +
                         $"{(int)ApIds.Characters.Akiyama},");
        for (var sh = 0; sh < ApIds.ShopDefs.Length; sh++)
        {
            var def = ApIds.ShopDefs[sh];
            if (!ApIds.Reachable(def.Who)) continue;
            for (var slot = 0; slot < def.Slots; slot++)
                b.AppendLine($"    {Py(ApIds.ShopLocationName(def, slot))}: {(int)def.Who},");
        }
        b.AppendLine("}");
        b.AppendLine();

        b.AppendLine("# item name -> characters who need it (0 = anyone)");
        b.AppendLine("ITEM_CHARACTERS = {");
        b.AppendLine($"    {Py("Erika's Business Card")}: {(int)ApIds.ItemCharacters(ApIds.ErikaCard)},");
        b.AppendLine($"    {Py("Yuna's Business Card")}: {(int)ApIds.ItemCharacters(ApIds.YunaCard)},");
        for (var i = 0; i < Abilities.Count; i++)
            b.AppendLine($"    {Py(Abilities.All[i].Name)}: " +
                         $"{(int)ApIds.ItemCharacters(ApIds.AbilityItemId(i))},");
        b.AppendLine("}");
        b.AppendLine();

        // Empty now that abilities are items only. Kept so the world can gate a
        // location on an item without another emitter change.
        b.AppendLine("# location name -> item name that must be received first");
        b.AppendLine("LOCATION_REQUIRES = {");
        b.AppendLine("}");
        b.AppendLine();

        b.AppendLine("HOSTESS_CARDS = (");
        b.AppendLine($"    {Py("Erika's Business Card")},");
        b.AppendLine($"    {Py("Yuna's Business Card")},");
        b.AppendLine(")");
        b.AppendLine();

        b.AppendLine("# location name -> the level it needs. The YAML caps which exist.");
        b.AppendLine("LEVEL_LOCATIONS = {");
        for (var level = 2; level <= ApIds.MaxLevel; level++)
            b.AppendLine($"    {Py(ApIds.LevelLocationName(level))}: {level},");
        b.AppendLine("}");
        b.AppendLine();

        b.AppendLine("ABILITY_ITEMS = (");
        for (var i = 0; i < Abilities.Count; i++)
            b.AppendLine($"    {Py(Abilities.All[i].Name)},");
        b.AppendLine(")");
        b.AppendLine();

        // Filler is picked kind-first then amount, so the generator emits the
        // ranges rather than one flat list - a uniform choice over every variant
        // would weight ammo 20:1 against soul points.
        b.AppendLine($"AMMO_MIN, AMMO_MAX = {ApIds.AmmoMin}, {ApIds.AmmoMax}");
        b.AppendLine($"AMMO_TYPES = ({string.Join(", ", ApIds.AmmoTypes.Select(a => Py(a.Name)))},)");
        b.AppendLine("VANILLA_SHOP_ITEMS = (");
        foreach (var id in ApIds.VanillaShopItems)
        {
            var nm = Inventory.KnownItems.TryGetValue(id, out var known) ? known : null;
            if (nm is null || Inventory.IsPlaceholder(nm)) continue;
            b.AppendLine($"    {Py(nm)},");
        }
        b.AppendLine(")");
        b.AppendLine();
        b.AppendLine("GUN_ITEMS = (");
        foreach (var (_, name) in ApIds.Guns) b.AppendLine($"    {Py(name)},");
        b.AppendLine(")");
        b.AppendLine();
        b.AppendLine("# locations that must never hold anything needed");
        b.AppendLine("EXCLUDED_LOCATIONS = (");
        for (var sh = 0; sh < ApIds.ShopDefs.Length; sh++)
        {
            var def = ApIds.ShopDefs[sh];
            if (!def.Excluded || !ApIds.Reachable(def.Who)) continue;
            for (var slot = 0; slot < def.Slots; slot++)
                b.AppendLine($"    {Py(ApIds.ShopLocationName(def, slot))},");
        }
        b.AppendLine(")");
        b.AppendLine($"MONEY_AMOUNTS = ({string.Join(", ", ApIds.MoneyAmounts)},)");
        b.AppendLine();
        b.AppendLine("def ammo_item_name(kind, rounds):");
        b.AppendLine("    return f\"{kind} ({rounds})\"");
        b.AppendLine();
        b.AppendLine("def money_item_name(yen):");
        b.AppendLine("    return f\"{yen:,} Yen\"");
        return b.ToString();
    }

    public static string Write(string worldDirectory)
    {
        Directory.CreateDirectory(worldDirectory);
        var path = Path.Combine(worldDirectory, "Data.py");
        File.WriteAllText(path, Render());
        return path;
    }
}
